import HomePage from "@/features/home/components/HomePage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return <HomePage />;
}
